import styled from '@emotion/styled'
import type { NextPage } from 'next'
import Head from 'next/head'

const Test = styled.div`
  color: ${({ theme }) => theme.semantic1};
  background-color: ${({ theme }) => theme.GRAY70};
`

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Test>hello</Test>
      </div>
    </>
  )
}

export default Home
